services:
  portainer:
    image: portainer/portainer-ce
    container_name: sm_portainer
    ports:
      - ${PORTAINER_PORT_OUTSIDE}:9000
      - 8000:8000
    volumes:
      - ./volumes/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      monitor_gid_network:
        ipv4_address: ${PORTAINER_IP}
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: sm_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_LOGIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_LOGIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT_OUTSIDE}:80
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      monitor_gid_network:
        ipv4_address: ${PGADMIN_IP}
  
  postgres:
    image: postgres:13.3
    container_name: sm_postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=America/Sao_Paulo
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_OUTSIDE}:5432
    networks:
      monitor_gid_network:
        ipv4_address: ${POSTGRES_IP}

networks:
  monitor_gid_network:
    driver: bridge
    name: state_machine_network
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
